image: python:3.9

before_script:
  - apt-get update -qq
  - apt-get install -y libpq-dev
  - pip install -r requirements.txt

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t flask_ci_app .

test:
  stage: test
  script:
    - docker run --rm flask_ci_app pytest
